# syntax=docker/dockerfile:1
FROM ubuntu:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim neovim
RUN apt-get install -y iputils-ping
RUN apt-get install -y curl
RUN pip3 install flask pika pymysql uuid requests Flask-JSGlue flask_cors pydantic bson pymongo flask_restful
RUN git clone https://API_TOKEN@github.com/TODO
EXPOSE 3306
EXPOSE 3307
