# syntax=docker/dockerfile:1
FROM ubuntu:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim neovim
RUN apt-get install -y iputils-ping
RUN apt-get install -y curl
RUN apt-get install -y fish
RUN pip3 install flask pika pymysql uuid requests Flask-JSGlue flask_cors \
    pydantic bson pymongo flask_restful ipython cryptography marshmallow \
    flask_login flask_wtf
RUN git clone https://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@github.com/skmnktl/web_dev_spring22_project.git
EXPOSE 3330
