# syntax=docker/dockerfile:1
FROM mysql:latest
RUN apt-get update 
RUN apt-get install -y git 
RUN apt-get install -y python3 
RUN apt-get install -y python3-pip
RUN apt-get install -y net-tools
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN apt-get install -y curl
RUN pip3 install flask pika pymysql uuid requests Flask-JSGlue flask_cors pydantic bson flask_restful
EXPOSE 3320
